version: '3'

services:
  nginx:
    container_name: ${NGINX_CONTAINER}
    image: ${IMAGE}
    platform: linux/amd64
    restart: always
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/sites/strapi/app:/opt/app
      - /root/sites/strapi/data:/opt/app/public/uploads
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: capitan27@puntapie.cl
    networks:
      - root_default

networks:
  root_default:
    external: true
